version: '2'

networks:
  isidore_network:
    external:
      name: nginxproxynetwork

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: isidore_es
    restart: always
    environment:
      - discovery.type=single-node
    expose:
      - 9200
    networks:
      - isidore_network
    volumes:
      - /data/docker/volumes/isidore_es/_data:/usr/share/elasticsearch/data
      - /home/robz:/home

  db:
    image: postgres:12
    container_name: isidore_postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /data/docker/volumes/isidore-postgres/_data:/var/lib/postgresql/data
      - /home/robz:/home
    environment:
      POSTGRES_USER: isidore
      POSTGRES_PASSWORD: rambo
      POSTGRES_DB: isidore
    networks:
      - isidore_network

  isidore:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: isidore_application
    restart: always
    environment:
      - VIRTUAL_HOST=isidore.sd.di.huc.knaw.nl
    links:
      - elastic
      - db
    volumes:
      - /home/robz:/home
    ports:
      - 8086:80
    networks:
      - isidore_network